import type { Metadata } from "next";
import {Sora} from 'next/font/google';
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-sora',
  display: 'swap',
  fallback: ['Helvetica', 'Arial', 'sans-serif'],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={sora.className}
      >
        {children}
      </body>
    </html>
  );
}
